SPINUP_DICE = Isaac.GetItemIdByName("Spinup Dice")
WEIGHTED_DICE = Isaac.GetItemIdByName("Weighted_Dice")
SATANIC_DICE = Isaac.GetItemIdByName("Satanic Dice")
EDEN_DICE = Isaac.GetItemIdByName("Eden Dice")
FAMILIAR_DICE = Isaac.GetItemIdByName("Familiar Dice")


--- SATANIC DICE ---
SATANIC_DICE_BOSSES = {
    EntityType.ENTITY_LITTLE_HORN,
    EntityType.ENTITY_LIL_BLUB,
    EntityType.ENTITY_RAINMAKER,
    EntityType.ENTITY_COLOSTOMIA,
    EntityType.ENTITY_MIN_MIN,

    EntityType.ENTITY_DARK_ONE,
    EntityType.ENTITY_BIG_HORN,
    EntityType.ENTITY_MEGA_MAW,
    EntityType.ENTITY_SINGE,
    EntityType.ENTITY_REAP_CREEP,

    EntityType.ENTITY_ADVERSARY,
    EntityType.ENTITY_PEEP,
    EntityType.ENTITY_SIREN,
    EntityType.ENTITY_HERETIC,
    EntityType.ENTITY_VISAGE,

    EntityType.ENTITY_PEEP,
    EntityType.ENTITY_MATRIARCH,
    EntityType.ENTITY_SCOURGE,
    EntityType.ENTITY_SATAN,
    EntityType.ENTITY_THE_LAMB
}


--- FAMILIARS - FAMILIAR DICE ---

FAMILIARS = {
    CollectibleType.COLLECTIBLE_CUBE_OF_MEAT,
    CollectibleType.COLLECTIBLE_BALL_OF_BANDAGES,
    CollectibleType.COLLECTIBLE_DADDY_LONGLEGS,
    CollectibleType.COLLECTIBLE_DEAD_BIRD,
    CollectibleType.COLLECTIBLE_GEMINI,
    CollectibleType.COLLECTIBLE_LEECH,
    CollectibleType.COLLECTIBLE_LIL_HAUNT,
    CollectibleType.COLLECTIBLE_LIL_BRIMSTONE,
    CollectibleType.COLLECTIBLE_SMART_FLY,
    CollectibleType.COLLECTIBLE_DRY_BABY,
    CollectibleType.COLLECTIBLE_JUICY_SACK,
    CollectibleType.COLLECTIBLE_ROBO_BABY_2,
    CollectibleType.COLLECTIBLE_ROTTEN_BABY,
    CollectibleType.COLLECTIBLE_HEADLESS_BABY,
    CollectibleType.COLLECTIBLE_MYSTERY_SACK,
    CollectibleType.COLLECTIBLE_BBF,
    CollectibleType.COLLECTIBLE_BOBS_BRAIN,
    CollectibleType.COLLECTIBLE_BEST_BUD,
    CollectibleType.COLLECTIBLE_ISAACS_HEART,
    CollectibleType.COLLECTIBLE_DARK_BUM,
    CollectibleType.COLLECTIBLE_BIG_FAN,
    CollectibleType.COLLECTIBLE_SISSY_LONGLEGS,
    CollectibleType.COLLECTIBLE_PUNCHING_BAG,
    CollectibleType.COLLECTIBLE_7_SEALS,
    CollectibleType.COLLECTIBLE_BIRD_CAGE,
    CollectibleType.COLLECTIBLE_BLOOD_PUPPY,
    CollectibleType.COLLECTIBLE_INTRUDER,
    CollectibleType.COLLECTIBLE_DISTANT_ADMIRATION,
    CollectibleType.COLLECTIBLE_FOREVER_ALONE,
    CollectibleType.COLLECTIBLE_GUARDIAN_ANGEL,
    CollectibleType.COLLECTIBLE_GUILLOTINE,
    CollectibleType.COLLECTIBLE_HALO_OF_FLIES,
    CollectibleType.COLLECTIBLE_SACRIFICIAL_DAGGER,
    CollectibleType.COLLECTIBLE_FRIEND_ZONE,
    CollectibleType.COLLECTIBLE_SWORN_PROTECTOR,
    CollectibleType.COLLECTIBLE_ANGELIC_PRISM,
    CollectibleType.COLLECTIBLE_BLOODSHOT_EYE,
    CollectibleType.COLLECTIBLE_LEPROSY,
    CollectibleType.COLLECTIBLE_MOMS_RAZOR,
    CollectibleType.COLLECTIBLE_SLIPPED_RIB,
    CollectibleType.COLLECTIBLE_BOT_FLY,
    CollectibleType.COLLECTIBLE_PSY_FLY,
    CollectibleType.COLLECTIBLE_SWARM,
    CollectibleType.COLLECTIBLE_TINYTOMA,
    CollectibleType.COLLECTIBLE_VENGEFUL_SPIRIT,
    CollectibleType.COLLECTIBLE_BOMB_BAG,
    CollectibleType.COLLECTIBLE_BUM_FRIEND,
    CollectibleType.COLLECTIBLE_LITTLE_CHAD,
    CollectibleType.COLLECTIBLE_SACK_OF_PENNIES,
    CollectibleType.COLLECTIBLE_RELIC,
    CollectibleType.COLLECTIBLE_BUMBO,
    CollectibleType.COLLECTIBLE_CHARGED_BABY,
    CollectibleType.COLLECTIBLE_KEY_BUM,
    CollectibleType.COLLECTIBLE_LIL_CHEST,
    CollectibleType.COLLECTIBLE_RUNE_BAG,
    CollectibleType.COLLECTIBLE_ACID_BABY,
    CollectibleType.COLLECTIBLE_SACK_OF_SACKS,
    CollectibleType.COLLECTIBLE_ABEL,
    CollectibleType.COLLECTIBLE_ABEL,
    CollectibleType.COLLECTIBLE_BROTHER_BOBBY,
    CollectibleType.COLLECTIBLE_CAINS_OTHER_EYE,
    CollectibleType.COLLECTIBLE_DEMON_BABY,
    CollectibleType.COLLECTIBLE_GHOST_BABY,
    CollectibleType.COLLECTIBLE_LITTLE_GISH,
    CollectibleType.COLLECTIBLE_LITTLE_STEVEN,
    CollectibleType.COLLECTIBLE_MONGO_BABY,
    CollectibleType.COLLECTIBLE_RAINBOW_BABY,
    CollectibleType.COLLECTIBLE_ROBO_BABY,
    CollectibleType.COLLECTIBLE_SISTER_MAGGY,
    CollectibleType.COLLECTIBLE_FATES_REWARD,
    CollectibleType.COLLECTIBLE_INCUBUS,
    CollectibleType.COLLECTIBLE_LIL_LOKI,
    CollectibleType.COLLECTIBLE_SERAPHIM,
    CollectibleType.COLLECTIBLE_BUDDY_IN_A_BOX,
    CollectibleType.COLLECTIBLE_LIL_MONSTRO,
    CollectibleType.COLLECTIBLE_LIL_SPEWER,
    CollectibleType.COLLECTIBLE_BOILED_BABY,
    CollectibleType.COLLECTIBLE_FREEZER_BABY,
    CollectibleType.COLLECTIBLE_GIANT_CELL,
    CollectibleType.COLLECTIBLE_LIL_ABADDON,
    CollectibleType.COLLECTIBLE_QUINTS,
    CollectibleType.COLLECTIBLE_TWISTED_PAIR,
    CollectibleType.COLLECTIBLE_SPIDER_MOD,
    CollectibleType.COLLECTIBLE_YO_LISTEN,
    CollectibleType.COLLECTIBLE_LIL_DUMPY,
    CollectibleType.COLLECTIBLE_PEEPER,
    CollectibleType.COLLECTIBLE_GB_BUG,
    CollectibleType.COLLECTIBLE_SUCCUBUS,
    CollectibleType.COLLECTIBLE_HUSHY,
    CollectibleType.COLLECTIBLE_MULTIDIMENSIONAL_BABY,
    CollectibleType.COLLECTIBLE_OBSESSED_FAN,
    CollectibleType.COLLECTIBLE_PAPA_FLY,
    CollectibleType.COLLECTIBLE_SHADE,
    CollectibleType.COLLECTIBLE_HOLY_WATER,
    CollectibleType.COLLECTIBLE_LITTLE_CHUBBY,
    CollectibleType.COLLECTIBLE_BIG_CHUBBY,
    CollectibleType.COLLECTIBLE_JAW_BONE,
    CollectibleType.COLLECTIBLE_LIL_PORTAL,
    CollectibleType.COLLECTIBLE_BLUE_BABYS_ONLY_FRIEND,
    CollectibleType.COLLECTIBLE_GUPPYS_HAIRBALL,
    CollectibleType.COLLECTIBLE_SAMSONS_CHAINS,
    CollectibleType.COLLECTIBLE_CENSER,
    CollectibleType.COLLECTIBLE_FARTING_BABY,
    CollectibleType.COLLECTIBLE_LIL_GURDY,
    CollectibleType.COLLECTIBLE_LOST_FLY,
    CollectibleType.COLLECTIBLE_MILK,
    CollectibleType.COLLECTIBLE_ANGRY_FLY,
    CollectibleType.COLLECTIBLE_DEPRESSION,
    CollectibleType.COLLECTIBLE_FINGER,
    CollectibleType.COLLECTIBLE_HALLOWED_GROUND,
    CollectibleType.COLLECTIBLE_KING_BABY,
    CollectibleType.COLLECTIBLE_LIL_DELIRIUM,
    CollectibleType.COLLECTIBLE_MYSTERY_EGG,
    CollectibleType.COLLECTIBLE_POINTY_RIB,
    CollectibleType.COLLECTIBLE_BLOOD_OATH,
    CollectibleType.COLLECTIBLE_CUBE_BABY,
    CollectibleType.COLLECTIBLE_FRUITY_PLUM,
    CollectibleType.COLLECTIBLE_LOST_SOUL,
    CollectibleType.COLLECTIBLE_STAR_OF_BETHLEHEM,
    CollectibleType.COLLECTIBLE_VANISHING_TWIN,
    CollectibleType.COLLECTIBLE_WORM_FRIEND
}